export {Title} from './Title/Title'
export {InputLog} from './FormInput/InputLog'
export {CardInfo}from './CardInfo/CardInfo'
export {LikedInfo}from './CardInfo/LikedInfo'
export {CheckBoxWithLabel} from './FormInput/Checkbox'
export {OR} from './FormInput/or'
export {CardList} from './CardInfo/CardList'
export {LikedList} from './CardInfo/LikedList'
export {CardGender} from './CardInfo/CardGender'