export {Title} from './Title/Title'
export {InputLog} from './FormInput/InputLog'
export {CardInfo}from './CardInfo/CardInfo'
export {CheckBoxWithLabel} from './FormInput/Checkbox'
export {OR} from './FormInput/or'
export {CardList} from './CardInfo/CardList'
export {CardGender} from './CardInfo/CardGender'